/**
 * @file ui.h
 * @brief Public interface for the User Interface (UI) subsystem.
 *
 * @details
 * The UI subsystem is responsible for:
 * - Handling button input (UP / DOWN / SELECT)
 * - Driving the LCD to display status and configuration
 * - Managing menus and simple navigation
 *
 * The main application interacts with the UI only through:
 * - ButtonEvent values from pollButtons()
 * - uiHandleEvent() to feed button events into the UI state machine
 * - uiInit() and uiLoop() for lifecycle management
 *
 * @defgroup UI User Interface Subsystem
 * @{
 */

#pragma once
#include <stdint.h>

/**
 * @brief Button events generated by the input polling logic.
 */
enum ButtonEvent : uint8_t {
    BTN_NONE = 0,  /**< No button event */
    BTN_UP,        /**< UP button pressed */
    BTN_DOWN,      /**< DOWN button pressed */
    BTN_SELECT     /**< SELECT/ENTER button pressed */
};

/**
 * @brief Initializes the UI subsystem (LCD, state, menus).
 *
 * @details
 * This should be called once from setup() after hardware is ready.
 */
void uiInit();

/**
 * @brief Polls the physical buttons and returns a debounced event.
 *
 * @details
 * - Returns BTN_NONE if no new event is available.
 * - Should be called once per loop() iteration.
 *
 * @return ButtonEvent representing the latest button press, or BTN_NONE.
 */
ButtonEvent pollButtons();

/**
 * @brief Feeds a button event into the UI state machine.
 *
 * @details
 * This function is responsible for:
 * - Navigating menus
 * - Triggering configuration changes
 * - Requesting actions (e.g., door pulse, manual light toggle)
 *
 * @param ev Button event to process.
 */
void uiHandleEvent(ButtonEvent ev);

/**
 * @brief Periodic UI processing and LCD refresh.
 *
 * @details
 * This should be called once per loop() iteration after control and actuators
 * have been updated. It is responsible for:
 * - Updating the current screen
 * - Refreshing the LCD at a reasonable rate
 */
void uiLoop();

/** @} */ // end of UI group